apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kcp.fullname" .}}-internal-admin-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: logical-cluster:admin
        cluster:
          # this references the CA certificate that signed kcp's serving certificate
          # (kcp-server-issuer by default)
          certificate-authority: /etc/kcp/tls/ca/tls.crt
          server: "https://{{ include "kcp.fullname" . }}:6443"
    contexts:
      - name: logical-cluster
        context:
          cluster: logical-cluster:admin
          user: logical-cluster-admin
    current-context: logical-cluster
    users:
      - name: logical-cluster-admin
        user:
          client-certificate: /etc/kcp/logical-cluster-admin/kubeconfig-client-cert/tls.crt
          client-key: /etc/kcp/logical-cluster-admin/kubeconfig-client-cert/tls.key

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kcp.fullname" . }}-external-admin-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: external-logical-cluster-admin
        cluster:
          # this references the CA certificate that signed the kcp-front-proxy's certificate
          # (kcp-server-issuer by default, but could also be any other, external CA)
          certificate-authority: /etc/kcp/tls/ca/tls.crt
          server: "https://{{ .Values.externalHostname }}:{{ if eq .Values.kcpFrontProxy.service.type "LoadBalancer" }}8443{{ else }}443{{- end }}"
    contexts:
      - name: external-logical-cluster
        context:
          cluster: external-logical-cluster-admin
          user: external-logical-cluster-admin
    current-context: external-logical-cluster
    users:
      - name: external-logical-cluster-admin
        user:
          client-certificate: /etc/kcp/external-logical-cluster-admin/kubeconfig-client-cert/tls.crt
          client-key: /etc/kcp/external-logical-cluster-admin/kubeconfig-client-cert/tls.key
