---

ansible_user: openshift
ansible_become: True

# Node Labels to use with the CASL tools
#openshift_node_labels: "{{ openstack.metadata.node_labels}}"

deployment_type: openshift-enterprise
openshift_deployment_type: openshift-enterprise
openshift_master_cluster_method: native
# OpenShift FQDNs, DNS, App domain specific configurations
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ dns_domain }}"
openshift_master_cluster_hostname: "master-0.{{ env_id }}.{{ dns_domain }}"
openshift_master_cluster_public_hostname: "console.{{ env_id }}.{{ dns_domain }}"

#openshift_deployment_type: openshift-enterprise
openshift_release: v3.11
osm_cluster_network_cidr: 10.128.0.0/14
openshift_portal_net: 172.30.0.0/16
openshift_master_ingress_ip_network_cidr: 192.168.97.0/24

#osm_default_node_selector: 'region=primary'
osm_use_cockpit: false
#osm_cockpit_plugins: 
#- 'cockpit-kubernetes'

os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
#os_firewall_use_firewalld: false

# HTPASSWD Identity Provider
openshift_master_identity_providers:
 - 'name': 'htpasswd_auth'
   'login': 'true'
   'challenge': 'true'
   'kind': 'HTPasswdPasswordIdentityProvider'
#   'filename': '/etc/origin/master/htpasswd'
   
openshift_master_htpasswd_users:
  admin: $apr1$7aiANAYb$TOUYVUqnBqBlD5AQEIMYw1   

#openshift_hosted_router_selector: 'region=infra'
openshift_hosted_manage_router: true

#openshift_hosted_registry_selector: 'region=infra'
openshift_hosted_manage_registry: true

# Deploy Logging with dynamic storage
openshift_logging_install_logging: false
openshift_logging_es_pvc_dynamic: true
openshift_logging_es_pvc_size: 40G
openshift_logging_curator_default_days: 1

# Deploy Metrics with dynamic storage
openshift_metrics_install_metrics: false
openshift_metrics_cassandra_storage_type: dynamic
openshift_metrics_cassandra_pvc_size: 40G
openshift_metrics_duration: 2

openshift_enable_service_catalog: true
openshift_hosted_prometheus_deploy: false
openshift_cfme_install_app: false 

openshift_docker_options: "--log-driver=json-file --log-opt max-size=50m --log-opt max-file=100"

openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
openshift_cloudprovider_openstack_username: "{{ lookup('env','OCP_OSP_USERNAME') }}"
openshift_cloudprovider_openstack_password: "{{ lookup('env','OCP_OSP_PASSWORD') }}"
openshift_cloudprovider_openstack_domain_name: Default
openshift_cloudprovider_openstack_tenant_id: "{{ lookup('env','OS_PROJECT_ID') }}"
openshift_cloudprovider_openstack_tenant_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
openshift_cloudprovider_openstack_region: "{{ lookup('env','OS_REGION_NAME') }}"
openshift_cloudprovider_openstack_lb_subnet_id: 7702e6d6-bba5-4e73-b0ee-467a33c78511
openshift_cloudprovider_openstack_blockstorage_version: v2



openshift_disable_check: 
  - docker_storage
  - memory_availability
  - disk_availability
  - docker_image_availability

#fix for recent bug
oreg_auth_user: "{{ lookup('env', 'RHN_USERNAME' )}}"
oreg_auth_password: "{{ lookup('env', 'RHN_PASSWORD' )}}"
#openshift_examples_modify_imagestreams: true

openshift_node_groups:
- name: node-config-master
  labels:
  - 'node-role.kubernetes.io/master=true'
  edits:
  - key: kubeletArguments.kube-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 50 }}M'
  - key: kubeletArguments.system-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 100 }}M'
- name: node-config-infra
  labels:
  - 'node-role.kubernetes.io/infra=true'
  edits:
  - key: kubeletArguments.kube-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 50 }}M'
  - key: kubeletArguments.system-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 100 }}M'
- name: node-config-compute
  labels:
  - 'node-role.kubernetes.io/compute=true'
  edits:
  - key: kubeletArguments.kube-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 50 }}M'
  - key: kubeletArguments.system-reserved
    value:
    - 'cpu={{ ansible_processor_vcpus * 50 }}m'
    - 'memory={{ ansible_processor_vcpus * 100 }}M'
