---

deployment_type: openshift-enterprise
openshift_deployment_type: openshift-enterprise
openshift_master_cluster_method: native
openshift_release: v3.9


# HTPASSWD Identity Provider
openshift_master_identity_providers:
 - 'name': 'htpasswd_auth'
   'login': 'true'
   'challenge': 'true'
   'kind': 'HTPasswdPasswordIdentityProvider'
   'filename': '/etc/origin/master/htpasswd'
   
openshift_master_htpasswd_users:
  admin: $apr1$7aiANAYb$TOUYVUqnBqBlD5AQEIMYw1   
  
osm_default_node_selector: 'region=primary'

openshift_docker_options: "--log-driver=json-file --log-opt max-size=50m --log-opt max-file=100"

openshift_cloudprovider_kind: gce

os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
os_firewall_use_firewalld: true
osm_cluster_network_cidr: 10.1.0.0/16

openshift_disable_check: 
  - memory_availability    
  - disk_availability    
  
openshift_use_crio: true
openshift_crio_enable_docker_gc: true  

openshift_hosted_router_selector: 'region=infra'
openshift_hosted_manage_router: true

openshift_hosted_registry_selector: 'region=infra'
openshift_hosted_manage_registry: true

openshift_logging_install_logging: true
openshift_logging_es_pvc_dynamic: true
openshift_logging_es_pvc_size: 10Gi
openshift_logging_es_cluster_size: 3
openshift_logging_es_number_of_replicas: 2
openshift_logging_kibana_replica_count: 2
openshift_logging_es_nodeselector: 
  region: infra
openshift_logging_kibana_nodeselector: 
  region: infra
openshift_logging_curator_nodeselector: 
  region: infra
openshift_logging_eventrouter_nodeselector:
  region: infra  
openshift_logging_fluentd_audit_container_engine: true
openshift_logging_install_eventrouter: true
openshift_logging_curator_default_days: 7

openshift_metrics_install_metrics: true
openshift_metrics_hawkular_nodeselector:
  region: infra
openshift_metrics_cassandra_nodeselector: 
  region: infra
openshift_metrics_heapster_nodeselector: 
  region: infra
openshift_metrics_hawkular_agent_nodeselector: 
  region: infra    
openshift_metrics_cassandra_storage_type: dynamic 
openshift_metrics_cassandra_pvc_size: 5Gi
openshift_metrics_hawkular_replicas: 2
openshift_metrics_cassandra_replicas: 3
openshift_metrics_install_hawkular_agent: true 

#service catalog
openshift_enable_service_catalog: true
#no decent storage option
ansible_service_broker_install: false
template_service_broker_install: true

  
  
#cloudforms settings
openshift_cfme_install_app: true
openshift_management_install_beta: true
openshift_management_app_template: cfme-template
openshift_management_storage_class: cloudprovider 

#prometheus
openshift_hosted_prometheus_deploy: false
openshift_prometheus_namespace: openshift-metrics
openshift_prometheus_node_selector: 
  region: infra
openshift_prometheus_storage_type: pvc
openshift_prometheus_alertmanager_storage_type: pvc
openshift_prometheus_alterbuffer_storage_type: pvc
openshift_prometheus_storage_class: standard
openshift_prometheus_alertmanager_storage_class: standard
openshift_prometheus_alterbuffer_storage_class: standard
openshift_prometheus_pvc_name: prometheus-data
openshift_prometheus_alertmanager_pvc_name: alertmanager-data
openshift_prometheus_alterbuffer_pvc_name: alertbuffer-data
openshift_prometheus_pvc_size: 3G
openshift_prometheus_alertmanager_pvc_size: 1G
openshift_prometheus_alertbuffer_pvc_size: 2G
  
  






