apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis-proxy.fullname" . }}-envoy-proxy
data:
  envoy.yaml: |  
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      secrets:
        - name: server_cert
          tls_certificate:
            certificate_chain:
              filename: /certs/tls.crt
            private_key:
              filename: /certs/tls.key      
      listeners: 
        - name: redis_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 6379        
          filter_chains:
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  tls_certificate_sds_secret_configs:
                  - name: server_cert        
            filters:
              - name: envoy.redis_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
                  stat_prefix: egress_redis
                  downstream_auth_password: 
                    inline_string: {{ .Values.password }}
                  prefix_routes:
                    catch_all_route: 
                      cluster: redis_cluster
                  settings:
                    op_timeout: 5s
      clusters:
      - name: redis_cluster
        connect_timeout: 1s
        type: strict_dns
        lb_policy: MAGLEV
        typed_extension_protocol_options:
          envoy.redis_proxy:
            "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
            auth_password: 
              inline_string: {{ .Values.password }}
        load_assignment:
          cluster_name: redis_cluster
          endpoints:
          - lb_endpoints:
{{- $fullname := .Values.fullnameOverride -}}            
{{- range until (int .Values.cluster.nodes) }}            
            - endpoint:
                address:
                  socket_address:
                    address: {{ $fullname }}-{{ . }}.{{ $fullname }}-headless
                    port_value: 6379
{{- end }}                    