apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-adp

resources:
  - oadp-tenant-route.yaml
  - rbac.yaml
  - credentials-velero-secret.yaml
  - data-protection.yaml
  - backup-schedule.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - routes.yaml
  - link.yaml

helmCharts:
  - name: tenant
    repo: https://operator.min.io
    releaseName: oadp
    namespace: openshift-adp
    valuesFile: values.yaml

  - name: vui
    repo: https://seriohub.github.io/velero-helm/
    releaseName: velero-ui
    namespace: openshift-adp
    valuesFile: vui-values.yaml        