apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configurations:
- overlays/istio/params.yaml
images:
- name: mysql
  newName: registry.redhat.io/rhscl/mysql-80-rhel7
  newTag: latest
kind: Kustomization
namespace: kubeflow
patchesJson6902:
- path: katib-mysql-Deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: katib-mysql
    version: v1
- path: katib-controller-Deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: katib-controller
    version: v1
patchesStrategicMerge:
- overlays/openshift/katib-mysql-secret.yaml
- overlays/openshift/katib-mysql-deployment-patch.yaml
resources:
- overlays/istio/katib-ui-virtual-service.yaml
